name: CI

on: [push, pull_request]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Run coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic -failfast ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4